os: osx
osx_image: xcode11.7
language: objective-c
xcode_project: SwiftStars.xcodeproj # path to your xcodeproj folder
xcode_scheme: SwiftStars
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

jobs:
  include:
  script:
      - echo "***** Testing for Alpha *****"
      - bundle exec fastlane setup