os: osx
osx_image: xcode11.7
language: objective-c
xcode_project: SwiftStars.xcodeproj # path to your xcodeproj folder
xcode_scheme: SwiftStars
#xcode_destination: platform:iOS Simulator, id:142BAAEC-D516-4D69-903A-A11D0B6214A7, OS:13.7, name:iPhone 11

jobs:
  include:
  command:
      - echo "***** Testing for Alpha *****"
      - bundle exec fastlane setup
      - xcodebuild -project SwiftStars.xcodeproj -scheme SwiftStars -sdk iphonesimulator -destination 'id=C80A1E5D-4531-4CC9-9C87-7C07D151C29B'